# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "classifier"
  s.version = "1.4.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Luis Parravicini"]
  s.date = "2012-04-27"
  s.description = "Bayesian, LSI classifier and others."
  s.email = "lparravi@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "Manifest",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "kitop-classifier.gemspec",
     "lib/classifier.rb",
     "lib/classifier/base.rb",
     "lib/classifier/bayes.rb",
     "lib/classifier/extensions/vector.rb",
     "lib/classifier/extensions/vector_serialize.rb",
     "lib/classifier/lsi.rb",
     "lib/classifier/lsi/content_node.rb",
     "lib/classifier/lsi/summary.rb",
     "lib/classifier/lsi/word_list.rb",
     "lib/classifier/stopwords.rb",
     "lib/classifier/stopwords/de",
     "lib/classifier/stopwords/en",
     "lib/classifier/stopwords/es",
     "lib/classifier/stopwords/ru",
     "lib/init.rb",
     "tasks/test.rake",
     "test/base_test.rb",
     "test/bayes/bayesian_test.rb",
     "test/lsi/lsi_test.rb",
     "test/stopwords_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/kitop/classifier"
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "A general classifier module to allow Bayesian and other types of classifications."
  s.test_files = [
    "test/base_test.rb",
     "test/bayes/bayesian_test.rb",
     "test/lsi/lsi_test.rb",
     "test/stopwords_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<ruby-stemmer>, [">= 0.5.1"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_dependency(%q<ruby-stemmer>, [">= 0.5.1"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.0.0"])
    s.add_dependency(%q<ruby-stemmer>, [">= 0.5.1"])
  end
end
